name: animated_sidebar
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animate_icons: ^2.0.0
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  custom_pop_up_menu: ^1.2.4
  el_tooltip: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  hydrated_bloc: ^9.1.0
  just_the_tooltip: ^0.0.12
  phosphor_flutter: ^1.4.0
  web_smooth_scroll: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 300
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
